### ISSUE TITLE
Dependency is not satisfiable: qt5-default

### ISSUE THREAD

**Issue by johnblommers** [JohnDTill/Forscape#128]
On PopOS 22.04 based on Ubuntu 22.04:

```
sudo gdebi forscape_0.0.1_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: qt5-default
```

There is no package `qt5-default` in the repository.

Update. This is [a work-around](https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04):

```
sudo apt-get update
sudo apt-get install equivs

cd ~/Downloads
cat <<EOF > qt5-default-control
Package: qt5-default
Source: qtbase-opensource-src
Version: 5.99.99+fake-13ubuntu37
Architecture: all
Depends: qtbase5-dev, qtchooser
Suggests: qt5-qmake, qtbase5-dev-tools
Conflicts: qt4-default
Section: libdevel
Priority: optional
Homepage: http://qt-project.org/
Description: Qt 5 development defaults fake package
EOF

equivs-build qt5-default-control
sudo apt-get install ./qt5-default_5.99.99+fake-13ubuntu37_all.deb
```

Then `sudo gdebi forscape_0.0.1_amd64.deb` installs. Launch the application using the name `Forscape`.

**Comment by JohnDTill** [comment]
To be honest, the .deb package is neglected compared to the windows .exe. There needs to be pipeline runner jobs to make the .deb and .exe artifacts, and verify that they work for target platforms.

In the mean time, you need to build from source to try the latest version.

**Comment by JohnDTill** [comment]
Actually qt5-default is universally discontinued, see https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04. The latest commit adds a runner job to verify the build instructions on Ubuntu, which would have also caught this PopOS unavailable dependency. Thanks for raising the issue- things will be smoother now that the install methods have regression tests.
